version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: | 
            gem install asciidoctor
            gem install asciidoctor-diagram
            pip3 install pyyaml
            pip3 install aura.tar.gz
            python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.7 --no-upstream-fetch && python3 makeBuild.py
            bash autopreview.sh
            bash autocomment.sh
          name: install and prereq
workflows:
  main:
    jobs:
      - build-and-test
