version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  install-deps:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip3 install aura.tar.gz
          name: Install Deps
workflows:
  main:
    jobs:
      - install-deps
