version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get install ruby rubygems
            sudo gem install asciidoctor asciidoctor-diagram
            pip3 install pyyaml
            pip3 install aura.tar.gz
            python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.5 --no-upstream-fetch && python3 makeBuild.py
            sudo bash ./autopreview.sh

workflows:
  main:
    jobs:
      - build-test
