version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  pre-build:
    executor: python/default
    steps: 
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      run: 
        - command: |
        gem install asciidoctor 
        gem install asciidoctor-diagram
        pip3 install pyyaml
        pip3 install aura.tar.gz
  build-and-test:
    steps:
      - run:
          command: python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.5 --no-upstream-fetch && python3 makeBuild.py
          name: Build
  post-build:
    steps:
      - run: autopreview.sh
workflows:
  main:
    jobs:
      - pre-build
      - build-and-test
      - post-build
